### ISSUE TITLE
List out of index

### ISSUE THREAD

**Issue by acpguedes** [LKremer/showTree#1]
> acpguedes@acpguedes-NH4CU03:~$ ./showTree/showTree.py -m blue.aln2 -t blue.tree -c blue.hmmscan -s 0.5 -o tree.svg
> compactseq
> Traceback (most recent call last):
>   File "./showTree/showTree.py", line 607, in <module>
>     lineseq=args.lineseq,
>   File "./showTree/showTree.py", line 517, in main
>     d.get_domain_annot_paths()
>   File "./showTree/showTree.py", line 101, in get_domain_annot_paths
>     dom_file_path = line.strip().split()[2]
> IndexError: list index out of range

**Comment by acpguedes** [comment]
I strongly recommend make your script accept hmmscan output format

> python3 showTree-master/showTree.py -t blue.tree -m blue.aln2 -d blue.hmmscan -o example.svg 

Above I used FastTree calculed tree, a MSA and a HMMER3 hmmscan output.

I received this error

> You manually specified the domain annotation(s):  
> 	blue.hmmscan  
>  
> Traceback (most recent call last):  
>   File "showTree-master/showTree.py", line 607, in <module>  
>     lineseq=args.lineseq,  
>   File "showTree-master/showTree.py", line 522, in main  
>     d.collect_domain_info()  
>   File "showTree-master/showTree.py", line 167, in collect_domain_info  
>     self.parse_domain_annotation(dom_annot_path)  
>   File "showTree-master/showTree.py", line 192, in parse_domain_annotation  
>     int(fields[1]), int(fields[2])  
> ValueError: invalid literal for int() with base 10: 'MNSISQISGNASATSGVTNEANVLSGEaVETMHAL--SKASEEIEAVVGLIQKI'  

The it's sound like you are waiting a different format that you didn't specified in your documentation.
Also, you ask for a calcTree configure file output witch community are not able to use.

Anyway, it works without -c and -d options. and worked well. Thanks

**Comment by LKremer** [comment]
Hi @acpguedes ,

the required domain input format is the output format of pfam_scan.pl which you can download here: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/Tools/
You don't need calcTree, it's an internal tool from my former colleagues. It wasn't so clear in the readme, I updated that now.

Here is an example of the domain input format, maybe you can somehow convert your file to this format?
[InR.pfam.txt](https://github.com/LKremer/showTree/files/2163671/InR.pfam.txt)

Alternatively I could try to implement an option to accept hmmscan files as well. Could you upload your file so I can see what the format looks like?

Cheers, Lukas
