### ISSUE TITLE
could you please upload the example files which you used in the picture?

### ISSUE THREAD

**Issue by weifei888** [LKremer/showTree#2]
could you please upload the example files which you used in the picture?

**Comment by LKremer** [comment]
Hi @weifei888 , unfortunately I couldn't find the exact files that I showed in the readme. But I added another suitable example data set to the repository. I hope this helps.
You can plot the data like this: 
`showTree.py -m InR_alignment.fa -t InR_tree.nwk -d InR_domains.pfam -s 0.3`

**Comment by weifei888** [comment]
Thank you for the reply, but I still get the error:
Traceback (most recent call last):
  File "showTree.py", line 14, in <module>
    from ete3 import Tree, TreeStyle, SeqMotifFace, NodeStyle
ImportError: cannot import name TreeStyle

but I already followed your steps of ete3 and biopython. did you miss some dependence in this script?

**Comment by weifei888** [comment]
i mean, should  i install some other dependence packages except the ete3 and biopython?

**Comment by LKremer** [comment]
Hi @weifei888 ,
I think I had this problem before when using a newer version of ete3. For some reason the TreeStyle object is no longer available in the latest ete3 version, even though they mention it in the documentation...

Can you run the following command from within python and tell me the output?
`import ete3`
`ete3.__version__`

**Comment by weifei888** [comment]
Thank you!
after i revise the script like you said, it didn't work
however after I install the ete3 by conda (my OS is deepinOS), it worked, i guess many packages i didn't mentioned like pyqt4 were installed at that time

**Comment by weifei888** [comment]
sorry i have another problem, in your example picture, the domain part is under the MSA part. 
however, in my output picture, the domain part is cover on the MSA part, should I change some code or something?

**Comment by LKremer** [comment]
This is normal, the picture shown in the readme was done with an older version of showTree. At some point I moved the domains on top of the MSA because I think it looks nicer (but of course you lose some MSA information). At some point I might add an option to plot the domains below the MSA again. 

For now what you could of course do is exporting the picture as PDF and then manually editing the picture by hand (with e.g. inkscape or adobe illustrator). Then you can drag the domains to where you want. It's a lot of work but if you only have one gene family it might be worth it.

**Comment by weifei888** [comment]
Thanks for your reply again, that very kind if you add that option.  And i think if you can add another option, this script would be great: when the user put the gff file, the extron of MSA part would be a border, the intron would be a line in the middle.

**Comment by LKremer** [comment]
You're right, that would be useful! I'm not working with gene trees at the moment though, so I don't really want to spend time on this right now. Pull requests are always welcome though.
